import type { Metadata } from 'next'
import './mdx.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app 14',
}

export default function RootLayout ({
  children,
}: {
    children: React.ReactNode
  }) {
  return children
}
